# Generated by Django 5.2.8 on 2026-09-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='skills',
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='education',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.TextField(default=''),
        ),
    ]
