# Generated by Django 5.0 on 2026-09-26 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_jobseeker_skills_alter_jobseeker_education_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='headline',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='skills',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(blank=True, to='accounts.skill'),
        ),
    ]
