# Generated by Django 5.0 on 2026-09-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_skill_jobseeker_user_alter_jobseeker_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='links',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='work_exp',
            field=models.TextField(blank=True),
        ),
    ]
